version: 2
# Build documentation in the docs/ directory with Sphinx
build:
  image: stable

sphinx:
  configuration: conf.py
  fail_on_warning: true

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf
  - htmlzip
  
python:
  version: 3.6.9
  install:
    - requirements: requirements.txt
