version: 2
# Build documentation in the docs/ directory with Sphinx
build:
  image: stable

sphinx:
  configuration: conf.py

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf
  - htmlzip
  
python:
  version: 3.8
  install:
    - requirements: requirements.txt
